baseURL = "https://kurotych.com"
theme = "PaperMod"
defaultContentLanguage = "en"
googleAnalytics = "G-HKDH744EMY"
enableRobotsTXT = false
displayFullLangName = true
title  = "Kurotych üá∫üá¶"

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[[params.socialIcons]]
name = "github"
url = "https://github.com/kurotych/"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/anatolii-kurotych/"

[[params.socialIcons]]
name = "email"
url = "mailto:akurotych@gmail.com"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/armatusmiles"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

[params.homeInfoMode]
enabled = true

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    [languages.en.params.homeInfoParams]
      Title = "Welcome"
      Content = "To my personal site. Here you can find information about me and my professional activity in software engineering."
    [[languages.en.menu.main]]
      name = "About Me"
      identifier = "about"
      url = "/about/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Certificates"
      identifier = "certificates"
      url = "/certificates/"
      weight = 2

  [languages.ua]
    languageName = "–£–∫—Ä–∞—ó–Ω—Å—å–∫–∞"
    languageCode = "uk"
    weight = 2
    [languages.ua.params.homeInfoParams]
      Title = "–õ–∞—Å–∫–∞–≤–æ –ø—Ä–æ—Å–∏–º–æ"
      Content = "–ù–∞ –º—ñ–π –ø–µ—Ä—Å–æ–Ω–∞–ª—å–Ω–∏–π —Å–∞–π—Ç. –¢—É—Ç –≤–∏ –º–æ–∂–µ—Ç–µ –∑–Ω–∞–π—Ç–∏ —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—é –ø—Ä–æ –º–µ–Ω–µ —Ç–∞ –º–æ—é –ø—Ä–æ—Ñ–µ—Å—ñ–π–Ω—É –¥—ñ—è–ª—å–Ω—ñ—Å—Ç—å —É —Å—Ñ–µ—Ä—ñ –ø—Ä–æ–≥—Ä–∞–º–Ω–æ—ó —ñ–Ω–∂–µ–Ω–µ—Ä—ñ—ó."
    [[languages.ua.menu.main]]
      name = "–ü—Ä–æ –º–µ–Ω–µ"
      identifier = "about"
      url = "/ua/about/"
      weight = 1
    [[languages.ua.menu.main]]
      name = "–°–µ—Ä—Ç–∏—Ñ—ñ–∫–∞—Ç–∏"
      identifier = "certificates"
      url = "/ua/certificates/"
      weight = 2
